spring:
  application:
    name: catalog-publish

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: catalog_user
    password: catalog_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: schema-pipeline-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 10000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        retry.backoff.ms: 1000
        delivery.timeout.ms: 120000
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 1
      type: SINGLE
      missing-topics-fatal: false

topics:
  input: events.input
  output: events.output
  dlt: events.dlt
  catalog:
    stored: catalog.items.stored

catalog:
  processing:
    batch-size: 100
    timeout-ms: 5000

kafka:
  topics:
    partitions: 3
    replication-factor: 1
  producer:
    sync-timeout-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.example.kafka: INFO
    org.springframework.kafka: INFO
